#!/bin/bash -e

job=$1

set -o pipefail

# TODO more nuanced caching policy
if output=$(./kgit rev-parse --verify -q refs/job/$job/last); then
    epoch=$(./kgit symbolic-ref refs/job/$job/last | cut -d/ -f4)
else
    epoch=$(<gen/epoch)
    # epoch is irrelevant for static outputs?
    if ! output=$(./kgit cat-file blob $job | grep -oP '(?<=^output=).*$'); then
        echo Running job $job >&2
        output=$(./kgit cat-file blob $job | ./run-job | ./kgit hash-object -w --stdin)
    fi
    ./kgit update-ref refs/job/$job/$epoch $output
    ./kgit symbolic-ref refs/job/$job/last refs/job/$job/$epoch
fi

echo $epoch $output
