#!/bin/bash -e

resource="$1"
resource_id=$(./kgit hash-object -w --stdin < "$resource")

if [[ -n $TRACING ]]; then
    echo 0000000000000000000000000000000000000000 $resource_id $resource >&2
fi

echo $resource_id
