#!/bin/bash -e

cat > gen/job.tmp

grep ^input_ gen/job.tmp | cut -d= -f2 | while read inputid; do
    ./kgit cat-file blob $inputid > gen/$inputid
done

IFS=$'\n'
exec env $(<gen/job.tmp) bash -c 'exec bash -c "$command"'
