#!/bin/bash -e
#
# Run a single job.

workdir=$(mktemp -d gen/job-XXXXXX)

cat > $workdir/job

grep ^input_ $workdir/job | cut -d= -f2 | while read inputid; do
    ./kgit cat-file blob $inputid > $workdir/$inputid
done

IFS=$'\n'
env -C $workdir $(<$workdir/job) bash -c 'exec bash -c "$command"'

rm -rf $workdir
