#!/bin/bash -ex

header() {
    echo -e "\n\033[32m$@\033[0m"
}

header basic
manifest=$(./run-flow flow/basic/tac.unit)
# difficult way to get the output
result=$(./kgit cat-file blob $manifest | tail -n1 | cut -d' ' -f3)
diff - <(./kgit cat-file blob $result) <<EOF
3
2
1
EOF

header reuse
manifest=$(./run-flow flow/reuse/abc.unit)
# difficult way to get the output
result=$(./kgit cat-file blob $manifest | tail -n1 | cut -d' ' -f3)
diff - <(./kgit cat-file blob $result) <<EOF
a
b
c
EOF

header PASS
