#!/usr/bin/python3

# should canonicalize, e.g., sort

import subprocess
import sys

for line in sys.stdin:
    key, value = line.rstrip().split('=', 1)
    if key.startswith('#'):
        continue
    elif key.startswith('input_'):
        inputid = subprocess.run(value, check=True, stdout=subprocess.PIPE,
                                 shell=True).stdout.strip().decode('ascii')
        assert len(inputid) == 40 and int(inputid, 16)
        print(f'{key}={inputid}')
    else:
        print(f'{key}={value}')
