#!/bin/bash -e

set -o pipefail

IFS=/ read -r empty pipeline_id <<< "$PATH_INFO"

echo Content-Type: text/html
echo

echo '<html><body>'

./kgit cat-file blob $pipeline_id | while read job_id result_id unit; do
    if [[ $job_id == 0000000000000000000000000000000000000000 ]]; then
        echo "<p><a href=\"/cgi-bin/cas/text/$result_id\">$unit</a>"
    else
        echo "<p><a href=\"/cgi-bin/cas/text/$job_id\">$unit</a> [<a href=\"/cgi-bin/cas/text/$result_id\">result</a>]"
        ./kgit cat-file blob $job_id | while IFS== read key value; do
            if [[ $key =~ input_* ]]; then
                echo "<br><a href=\"/cgi-bin/cas/text/$value\">$key</a>"
            fi
        done
    fi
done

echo '</body></html>'
