#!/bin/bash -e

set -o pipefail

IFS=/ read -r empty pipeline_id sub_action <<< "$PATH_INFO"

if [[ $sub_action == result ]]; then
    result_id=$(./kgit cat-file blob $pipeline_id | tail -n1 | cut -d' ' -f2)
    echo Content-Type: text/html
    echo
    if [[ $(./kgit cat-file -s $result_id) -gt 1000000 ]]; then
        echo "<a href=\"/cgi-bin/cas/html/$result_id\">load</a>"
    else
        ./kgit cat-file blob $result_id
    fi
    exit
elif [[ $sub_action == env-run ]]; then
    sid=$(./kgit cat-file blob $pipeline_id | ./pipeline-to-session)
    (
        cd gen/session/$sid
        target="$(python3 ../../../cgi-bin/form_to_env.py)"
        pipeline_id=$(./run-pipeline "$target")
        bash ../../../cgi-bin/redirect.sh /cgi-bin/pipeline/$pipeline_id
    )
    rm -rf "gen/session/$sid"
    exit
fi

echo Content-Type: text/html
echo

echo '<html><body>'

echo "<iframe src=\"$SCRIPT_NAME$PATH_INFO/result\" style=\"width: 100%; height: 65%; border: 1px solid black\"></iframe>"

echo '<form method=post action="/cgi-bin/new-session">'
echo "<input type=hidden name=pipeline_id value=$pipeline_id>"
echo '<input type=submit value=edit></form>'

./kgit cat-file blob $pipeline_id | while read job_id result_id unit; do
    if [[ $job_id == 0000000000000000000000000000000000000000 ]]; then
        echo "<p><a href=\"/cgi-bin/cas/text/$result_id\">$unit</a>"
    else
        echo "<p><a href=\"/cgi-bin/cas/text/$job_id\">$unit</a> [<a href=\"/cgi-bin/cas/text/$result_id\">result</a>]"
        ./kgit cat-file blob $job_id | while IFS== read key value; do
            if [[ $key =~ ^input_ ]]; then
                echo "<br><a href=\"/cgi-bin/cas/text/$value\">$key</a>"
            fi
        done
    fi
done

echo '</body></html>'
