#!/bin/bash -e

IFS=/ read -r empty sid sub_action sub_id <<< "$PATH_INFO"

if [[ -z $sub_action ]]; then
    echo Content-Type: text/html
    echo

    echo '<html><body>'

    while read input_id resource_id resource; do
        echo "<p><a href=\"$SCRIPT_NAME$PATH_INFO/resource/$resource\">$resource</a>"
        if [[ $resource =~ \.unit$ ]]; then
            echo "<br><a href=\"$SCRIPT_NAME$PATH_INFO/run/$resource\">run &gt;</a>"
        fi
    done < gen/session/$sid/manifest

    echo '</body></html>'
elif [[ $sub_action == run ]]; then
    pipeline_id=$(cd gen/session/$sid && rm -f "${sub_id%.unit}"{.job,.result} && ./run-pipeline "$sub_id")
    bash cgi-bin/redirect.sh /cgi-bin/pipeline/$pipeline_id
elif [[ $sub_action == resource ]]; then
    python3 cgi-bin/session_resource.py $sid "$sub_id"
fi
